---
title: "Subadult Age and Sex Estimation Report"
---

```{r setup, echo=FALSE, message=FALSE}
library(pander)
library(caret)
library(dplyr)
```

Generated by kidstats on `r Sys.Date()`

----

## Input

- Reference sample: **`r switch(input$refsamp, 'za' = 'South Africa')`**
- Transformation on Age: **`r switch(input$transform, 'none' = 'None', 'sqrt' = 'Square root', 'cbrt' = 'Cube root')`**

<br>

#### Input measurements

|           | Diaphyseal Length | Proximal Breadth | Midshaft Breadth | Distal Breadth |
| :-------- | :---------------: | :--------------: | :--------------: | :------------: |
|   Femur   |   `r input$fdl`   |                  |  `r input$fmsb`  |  `r input$fdb` |
|   Tibia   |   `r input$tdl`   |   `r input$tpb`  |  `r input$tmsb`  |  `r input$tdb` |
|   Humerus |   `r input$hdl`   |   `r input$hpb`  |  `r input$hmsb`  |  `r input$hdb` |
|   Radius  |   `r input$rdl`   |   `r input$rpb`  |  `r input$rmsb`  |  `r input$rdb` |
|   Ulna    |   `r input$udl`   |                  |  `r input$umsb`  |                |

<br>

----

## Age

### Estimation

| Lower Prediction Interval |         Estimated Age        |  Upper Prediction Interval |
| :-----------------------: | :--------------------------: | :------------------------: |
|  `r earth_mod()[[2]][2]`  | **`r earth_mod()[[2]][1]`**  |   `r earth_mod()[[2]][3]`  |

<br>

### Model

- Sample size used to model: **`r nrow(refsamp())`**
- Age model Generalized R^2: **`r round(earth_mod()[[1]]$grsq, digits = 4)`**

<br>

#### Coefficients and Hinge Points

```{r echo=FALSE, message=FALSE}
hinges <- add_rownames(data.frame(earth_mod()[[1]]$cuts), "Coefficients")
hinges <- hinges[earth_mod()[[1]]$selected.terms,]
pander(hinges)
```

<br>

